version: "3.7"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "10.181.4.1"
    ipam:
      driver: default
      config:
        - subnet: 10.181.4.0/28

services:
  frontend: 
    depends_on: 
      - auchandrive
    build: frontend/
    ports:
      - "80:3000"
    environment:
      AUCHANDRIVE_SERVICE_HOST: auchandrive
      AUCHANDRIVE_SERVICE_PORT: 8080

  auchandrive: 
    build: auchandrive/
    command:
      - "930"
    ports:
      - "8080"

  