version: "3.7"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "10.181.4.1"
    ipam:
      driver: default
      config:
        - subnet: 10.181.4.0/28

services:
  frontend: 
    depends_on: 
      - auchandrive
      - carrefourdrive
    build: frontend/
    ports:
      - "80:3000"
    environment:
      AUCHANDRIVE_SERVICE_HOST: auchandrive
      AUCHANDRIVE_SERVICE_PORT: 8080
      CARREFOURDRIVE_SERVICE_HOST: carrefourdrive
      CARREFOURDRIVE_SERVICE_PORT: 8080

  auchandrive: 
    build: auchandrive/
    env_file:
      - auchandrive/woos-vars.env
    ports:
      - "8080"

  carrefourdrive: 
    build: carrefourdrive/
    ports:
      - "8080"
  